### ISSUE TITLE
Freebsd 11.1 Openssh 7.2 regex only matches every 3 tries

### ISSUE THREAD

**Issue by repcsi** [dgerzo/bruteforceblocker#4]
It seems that the regex matching does not work as it should be on the above mentioned config.
So when you have max_attempts set to 3 it was only catched tries on the 9th or 10th login.
In the part commented as "the core process" where you match the log lines I added the following line after the first one which for me solved this issue: 
/.*Failed keyboard.*from ($work->{ipv4}|$work->{ipv6}|$work->{fqdn}) port.*/i ||

Thx!
Regards,
Repcsi

**Comment by dgerzo** [comment]
Hi, please send me a snippet of the log file that does not match for you.

**Comment by repcsi** [comment]
Hey, sent it to your mail!

**Comment by repcsi** [comment]
Hello Daniel,
Did you get the mail?

**Comment by dgerzo** [comment]
I guess this is resolved in 1.2.6 now
